
import os

HTML_DIR = "/Users/alexgarrison/Downloads/HockeyData/raw_html"
if not os.path.exists(HTML_DIR):
    os.makedirs(HTML_DIR)

content = """
<table class="sortable stats_table now_sortable" id="games" data-cols-to-freeze=",2">
    <caption>Regular Season Table</caption>
   <thead>      
      <tr>
         <th aria-label="GP" data-stat="games" scope="col" class=" poptip sort_default_asc center" data-tip="Games Played">GP</th>
         <th aria-label="Date" data-stat="date_game" scope="col" class=" poptip sort_default_asc left">Date</th>
         <th aria-label=" " data-stat="game_location" scope="col" class=" poptip left"></th>
         <th aria-label="Opponent" data-stat="opp_name" scope="col" class=" poptip sort_default_asc left">Opponent</th>
         <th aria-label="GF" data-stat="goals" scope="col" class=" poptip center" data-tip="Goals">GF</th>
         <th aria-label="GA" data-stat="opp_goals" scope="col" class=" poptip center">GA</th>
         <th aria-label=" " data-stat="game_outcome" scope="col" class=" poptip left"></th>
         <th aria-label=" " data-stat="overtimes" scope="col" class=" poptip center"></th>
         <th aria-label="W" data-stat="wins" scope="col" class=" poptip center" data-tip="Wins">W</th>
         <th aria-label="L" data-stat="losses" scope="col" class=" poptip center" data-tip="Losses">L</th>
         <th aria-label="OL" data-stat="losses_ot" scope="col" class=" poptip center" data-tip="Overtime/Shootout Losses (2000 season onward)">OL</th>
         <th aria-label="Streak" data-stat="game_streak" scope="col" class=" poptip sorttable_nosort left">Streak</th>
         <th aria-label="Att." data-stat="attendance" scope="col" class=" poptip center" data-tip="Attendance">Att.</th>
         <th aria-label="LOG" data-stat="game_duration" scope="col" class=" poptip right" data-tip="Length of Game">LOG</th>
         <th aria-label="Notes" data-stat="game_remarks" scope="col" class=" poptip sort_default_asc show_partial_when_sorting left">Notes</th>
      </tr>
      </thead>
<tbody><tr data-row="0"><th scope="row" class="right " data-stat="games">1</th><td class="left " data-stat="date_game"><a href="/boxscores/202410120SJS.html">2024-10-12</a></td><td class="left " data-stat="game_location">@</td><td class="left " data-stat="opp_name" csk="SJS2024-10-12"><a href="/teams/SJS/2025.html">San Jose Sharks</a></td><td class="right " data-stat="goals">2</td><td class="right iz" data-stat="opp_goals">0</td><td class="left " data-stat="game_outcome">W</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">1</td><td class="right iz" data-stat="losses">0</td><td class="right iz" data-stat="losses_ot">0</td><td class="left " data-stat="game_streak">W 1</td><td class="right " data-stat="attendance">17,016</td><td class="right " data-stat="game_duration">2:28</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="1"><th scope="row" class="right " data-stat="games">2</th><td class="left " data-stat="date_game"><a href="/boxscores/202410130VEG.html">2024-10-13</a></td><td class="left " data-stat="game_location">@</td><td class="left " data-stat="opp_name" csk="VEG2024-10-13"><a href="/teams/VEG/2025.html">Vegas Golden Knights</a></td><td class="right " data-stat="goals">1</td><td class="right " data-stat="opp_goals">3</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">1</td><td class="right " data-stat="losses">1</td><td class="right iz" data-stat="losses_ot">0</td><td class="left " data-stat="game_streak">L 1</td><td class="right " data-stat="attendance">18,027</td><td class="right " data-stat="game_duration">2:19</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="2"><th scope="row" class="right " data-stat="games">3</th><td class="left " data-stat="date_game"><a href="/boxscores/202410160ANA.html">2024-10-16</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="UTA2024-10-16"><a href="/teams/UTA/2025.html">Utah Hockey Club</a></td><td class="right " data-stat="goals">5</td><td class="right " data-stat="opp_goals">4</td><td class="left " data-stat="game_outcome">W</td><td class="center " data-stat="overtimes" csk="1">OT</td><td class="right " data-stat="wins">2</td><td class="right " data-stat="losses">1</td><td class="right iz" data-stat="losses_ot">0</td><td class="left " data-stat="game_streak">W 1</td><td class="right " data-stat="attendance">17,245</td><td class="right " data-stat="game_duration">2:44</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="4"><th scope="row" class="right " data-stat="games">5</th><td class="left " data-stat="date_game"><a href="/boxscores/202410200ANA.html">2024-10-20</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="LAK2024-10-20"><a href="/teams/LAK/2025.html">Los Angeles Kings</a></td><td class="right " data-stat="goals">1</td><td class="right " data-stat="opp_goals">4</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">2</td><td class="right " data-stat="losses">2</td><td class="right " data-stat="losses_ot">1</td><td class="left " data-stat="game_streak">L 2</td><td class="right " data-stat="attendance">16,098</td><td class="right " data-stat="game_duration">2:22</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="5"><th scope="row" class="right " data-stat="games">6</th><td class="left " data-stat="date_game"><a href="/boxscores/202410220ANA.html">2024-10-22</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="SJS2024-10-22"><a href="/teams/SJS/2025.html">San Jose Sharks</a></td><td class="right " data-stat="goals">3</td><td class="right " data-stat="opp_goals">1</td><td class="left " data-stat="game_outcome">W</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">3</td><td class="right " data-stat="losses">2</td><td class="right " data-stat="losses_ot">1</td><td class="left " data-stat="game_streak">W 1</td><td class="right " data-stat="attendance">17,174</td><td class="right " data-stat="game_duration">2:40</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="10"><th scope="row" class="right " data-stat="games">11</th><td class="left " data-stat="date_game"><a href="/boxscores/202411030ANA.html">2024-11-03</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="CHI2024-11-03"><a href="/teams/CHI/2025.html">Chicago Blackhawks</a></td><td class="right " data-stat="goals">2</td><td class="right " data-stat="opp_goals">4</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">4</td><td class="right " data-stat="losses">5</td><td class="right " data-stat="losses_ot">2</td><td class="left " data-stat="game_streak">L 2</td><td class="right " data-stat="attendance">16,352</td><td class="right " data-stat="game_duration">2:23</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="11"><th scope="row" class="right " data-stat="games">12</th><td class="left " data-stat="date_game"><a href="/boxscores/202411050ANA.html">2024-11-05</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="VAN2024-11-05"><a href="/teams/VAN/2025.html">Vancouver Canucks</a></td><td class="right " data-stat="goals">1</td><td class="right " data-stat="opp_goals">5</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">4</td><td class="right " data-stat="losses">6</td><td class="right " data-stat="losses_ot">2</td><td class="left " data-stat="game_streak">L 3</td><td class="right " data-stat="attendance">13,538</td><td class="right " data-stat="game_duration">2:30</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="12"><th scope="row" class="right " data-stat="games">13</th><td class="left " data-stat="date_game"><a href="/boxscores/202411080ANA.html">2024-11-08</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="MIN2024-11-08"><a href="/teams/MIN/2025.html">Minnesota Wild</a></td><td class="right " data-stat="goals">2</td><td class="right " data-stat="opp_goals">5</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">4</td><td class="right " data-stat="losses">7</td><td class="right " data-stat="losses_ot">2</td><td class="left " data-stat="game_streak">L 4</td><td class="right " data-stat="attendance">14,706</td><td class="right " data-stat="game_duration">2:22</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="13"><th scope="row" class="right " data-stat="games">14</th><td class="left " data-stat="date_game"><a href="/boxscores/202411100ANA.html">2024-11-10</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="CBJ2024-11-10"><a href="/teams/CBJ/2025.html">Columbus Blue Jackets</a></td><td class="right " data-stat="goals">4</td><td class="right " data-stat="opp_goals">2</td><td class="left " data-stat="game_outcome">W</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">5</td><td class="right " data-stat="losses">7</td><td class="right " data-stat="losses_ot">2</td><td class="left " data-stat="game_streak">W 1</td><td class="right " data-stat="attendance">16,153</td><td class="right " data-stat="game_duration">2:27</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="14"><th scope="row" class="right " data-stat="games">15</th><td class="left " data-stat="date_game"><a href="/boxscores/202411130ANA.html">2024-11-13</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="VEG2024-11-13"><a href="/teams/VEG/2025.html">Vegas Golden Knights</a></td><td class="right " data-stat="goals">2</td><td class="right " data-stat="opp_goals">3</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">5</td><td class="right " data-stat="losses">8</td><td class="right " data-stat="losses_ot">2</td><td class="left " data-stat="game_streak">L 1</td><td class="right " data-stat="attendance">13,153</td><td class="right " data-stat="game_duration">2:25</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="15"><th scope="row" class="right " data-stat="games">16</th><td class="left " data-stat="date_game"><a href="/boxscores/202411150ANA.html">2024-11-15</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="DET2024-11-15"><a href="/teams/DET/2025.html">Detroit Red Wings</a></td><td class="right " data-stat="goals">6</td><td class="right " data-stat="opp_goals">4</td><td class="left " data-stat="game_outcome">W</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">6</td><td class="right " data-stat="losses">8</td><td class="right " data-stat="losses_ot">2</td><td class="left " data-stat="game_streak">W 1</td><td class="right " data-stat="attendance">14,154</td><td class="right " data-stat="game_duration">2:29</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="18"><th scope="row" class="right " data-stat="games">19</th><td class="left " data-stat="date_game"><a href="/boxscores/202411220ANA.html">2024-11-22</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="BUF2024-11-22"><a href="/teams/BUF/2025.html">Buffalo Sabres</a></td><td class="right " data-stat="goals">2</td><td class="right " data-stat="opp_goals">3</td><td class="left " data-stat="game_outcome">L</td><td class="center " data-stat="overtimes" csk="1">OT</td><td class="right " data-stat="wins">8</td><td class="right " data-stat="losses">8</td><td class="right " data-stat="losses_ot">3</td><td class="left " data-stat="game_streak">L 1</td><td class="right " data-stat="attendance">13,776</td><td class="right " data-stat="game_duration">2:27</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="19"><th scope="row" class="right " data-stat="games">20</th><td class="left " data-stat="date_game"><a href="/boxscores/202411250ANA.html">2024-11-25</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="SEA2024-11-25"><a href="/teams/SEA/2025.html">Seattle Kraken</a></td><td class="right " data-stat="goals">2</td><td class="right " data-stat="opp_goals">3</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">8</td><td class="right " data-stat="losses">9</td><td class="right " data-stat="losses_ot">3</td><td class="left " data-stat="game_streak">L 2</td><td class="right " data-stat="attendance">15,331</td><td class="right " data-stat="game_duration">2:27</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="21"><th scope="row" class="right " data-stat="games">22</th><td class="left " data-stat="date_game"><a href="/boxscores/202411290ANA.html">2024-11-29</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="LAK2024-11-29"><a href="/teams/LAK/2025.html">Los Angeles Kings</a></td><td class="right " data-stat="goals">1</td><td class="right " data-stat="opp_goals">2</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">9</td><td class="right " data-stat="losses">10</td><td class="right " data-stat="losses_ot">3</td><td class="left " data-stat="game_streak">L 1</td><td class="right " data-stat="attendance">17,174</td><td class="right " data-stat="game_duration">2:25</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="22"><th scope="row" class="right " data-stat="games">23</th><td class="left " data-stat="date_game"><a href="/boxscores/202412010ANA.html">2024-12-01</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="OTT2024-12-01"><a href="/teams/OTT/2025.html">Ottawa Senators</a></td><td class="right " data-stat="goals">4</td><td class="right " data-stat="opp_goals">3</td><td class="left " data-stat="game_outcome">W</td><td class="center " data-stat="overtimes" csk="1">SO</td><td class="right " data-stat="wins">10</td><td class="right " data-stat="losses">10</td><td class="right " data-stat="losses_ot">3</td><td class="left " data-stat="game_streak">W 1</td><td class="right " data-stat="attendance">15,144</td><td class="right " data-stat="game_duration">2:39</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="23"><th scope="row" class="right " data-stat="games">24</th><td class="left " data-stat="date_game"><a href="/boxscores/202412040ANA.html">2024-12-04</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="VEG2024-12-04"><a href="/teams/VEG/2025.html">Vegas Golden Knights</a></td><td class="right " data-stat="goals">1</td><td class="right " data-stat="opp_goals">4</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">10</td><td class="right " data-stat="losses">11</td><td class="right " data-stat="losses_ot">3</td><td class="left " data-stat="game_streak">L 1</td><td class="right " data-stat="attendance">13,188</td><td class="right " data-stat="game_duration">2:23</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="24"><th scope="row" class="right " data-stat="games">25</th><td class="left " data-stat="date_game"><a href="/boxscores/202412060ANA.html">2024-12-06</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="MIN2024-12-06"><a href="/teams/MIN/2025.html">Minnesota Wild</a></td><td class="right " data-stat="goals">1</td><td class="right " data-stat="opp_goals">5</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">10</td><td class="right " data-stat="losses">12</td><td class="right " data-stat="losses_ot">3</td><td class="left " data-stat="game_streak">L 2</td><td class="right " data-stat="attendance">15,171</td><td class="right " data-stat="game_duration">2:28</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="29"><th scope="row" class="right " data-stat="games">30</th><td class="left " data-stat="date_game"><a href="/boxscores/202412180ANA.html">2024-12-18</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="WPG2024-12-18"><a href="/teams/WPG/2025.html">Winnipeg Jets</a></td><td class="right " data-stat="goals">3</td><td class="right " data-stat="opp_goals">2</td><td class="left " data-stat="game_outcome">W</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">12</td><td class="right " data-stat="losses">14</td><td class="right " data-stat="losses_ot">4</td><td class="left " data-stat="game_streak">W 2</td><td class="right " data-stat="attendance">16,260</td><td class="right " data-stat="game_duration">2:30</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="31"><th scope="row" class="right " data-stat="games">31</th><td class="left " data-stat="date_game"><a href="/boxscores/202412200ANA.html">2024-12-20</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="COL2024-12-20"><a href="/teams/COL/2025.html">Colorado Avalanche</a></td><td class="right " data-stat="goals">2</td><td class="right " data-stat="opp_goals">4</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">12</td><td class="right " data-stat="losses">15</td><td class="right " data-stat="losses_ot">4</td><td class="left " data-stat="game_streak">L 1</td><td class="right " data-stat="attendance">16,226</td><td class="right " data-stat="game_duration">2:31</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="34"><th scope="row" class="right " data-stat="games">34</th><td class="left " data-stat="date_game"><a href="/boxscores/202412280ANA.html">2024-12-28</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="PHI2024-12-28"><a href="/teams/PHI/2025.html">Philadelphia Flyers</a></td><td class="right " data-stat="goals">1</td><td class="right " data-stat="opp_goals">3</td><td class="left " data-stat="game_outcome">L</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">13</td><td class="right " data-stat="losses">17</td><td class="right " data-stat="losses_ot">4</td><td class="left " data-stat="game_streak">L 2</td><td class="right " data-stat="attendance">16,472</td><td class="right " data-stat="game_duration">2:24</td><td class="left iz" data-stat="game_remarks"></td></tr>
<tr data-row="35"><th scope="row" class="right " data-stat="games">35</th><td class="left " data-stat="date_game"><a href="/boxscores/202412290ANA.html">2024-12-29</a></td><td class="left iz" data-stat="game_location"></td><td class="left " data-stat="opp_name" csk="EDM2024-12-29"><a href="/teams/EDM/2025.html">Edmonton Oilers</a></td><td class="right " data-stat="goals">5</td><td class="right " data-stat="opp_goals">3</td><td class="left " data-stat="game_outcome">W</td><td class="center iz" data-stat="overtimes" csk="0"></td><td class="right " data-stat="wins">14</td><td class="right " data-stat="losses">17</td><td class="right " data-stat="losses_ot">4</td><td class="left " data-stat="game_streak">W 1</td><td class="right " data-stat="attendance">17,446</td><td class="right " data-stat="game_duration">2:32</td><td class="left iz" data-stat="game_remarks"></td></tr>

</tbody></table>
"""

with open(os.path.join(HTML_DIR, "2025_ANA.html"), 'w') as f:
    f.write(content)
    
print("Created sample 2025_ANA.html")
